baseURL = 'https://bytejamuary.creativenucleus.com/'
languageCode = 'en-gb'
theme = 'ananke'
copyright = 'James Rutherford (jtruk)'
title = '#ByteJamuary'
description = 'A Month of Daily ByteJam Tricks'

[params]
    custom_css = ["css/custom.css"]
    body_classes = [""]

[params.ananke.social.mastodon]
    username = "jtruk"
    profilelink = "https://mastodon.social/@jtruk"
[params.ananke.social.bluesky]
    username = "jtruk"
    profilelink = "https://bsky.app/profile/jtruk.bsky.social"
[params.ananke.social.github]
    username = "creativenucleus"
    profilelink = "https://github.com/creativenucleus"
[params.ananke.social.follow]
    new_window_icon = false
    networks = [
        "mastodon",
        "bluesky",
        "github",
    ]